theory  PRJ_12_04_06_04__EXIT
imports
  FUNCTION_CFG_ENFORCE_ACCESSIBILITY_cfgLM
  FUNCTION_CFG_ENFORCE_ACCESSIBILITY_cfgLM_EXTRA
  FUNCTION_CFG_ENFORCE_ACCESSIBILITY_cfgSTD
  PRJ_12_04_06_04__ENTRY
begin
(*automatically created; do not modify*)
end
